### PR TITLE
no-jira: Fix dockerfile

### PR DESCRIPTION
**Pull request by ingvagabund**
SSIA

### CODE REVIEW

**Comment by evakhoni** [comment]
> @[openshift-ci](https://github.com/apps/openshift-ci) openshift-ci bot assigned [evakhoni](https://github.com/evakhoni) [Nov 27, 2024](https://github.com/openshift/run-once-duration-override/pull/41#event-15452344326)

please stop this. received over 30 notifications just today from oc, for PRs that i have nothing to do with

**Comment by evakhoni** [comment]
opened https://github.com/openshift/release/pull/59284

**Comment by ingvagabund** [comment]
@evakhoni apologies for the noise. I do not know why you are getting assigned here. This is part of Konflux onboarding and there's not much I can do about the noise. Please, feel free to filter out any email notification coming from this repository.

**Comment by evakhoni** [comment]
ok. hope my pr removing myself from the tags will clam the bot.

**Pull request merged**
