### PR TITLE
WRKLDS-700: bump(k8s) to v0.27.1

### PR DESCRIPTION
**Pull request by ardaguclu**
This PR bumps k8s dependencies to v1.27.1.

### CODE REVIEW

**Comment by ardaguclu** [comment]
/test e2e-aws-operator 
to ensure flaky or real

**Comment by ingvagabund** [comment]
```
E0510 16:28:41.097271       1 run.go:74] "command failed" err="unable to install api resources: unable to setup API &{[admission.runoncedurationoverride.openshift.io/v1] map[v1:map[runoncedurationoverrides:0xc000295e30]] v1 <nil> 0xc00020df10 {0xc00020df10 0xc00028c480 [{application/json application json true 0xc0002aefa0 0xc0002aeff0 0xc0002af040 0xc0002724e0} {application/yaml application yaml true 0xc0002af090 <nil> 0xc0002af0e0 <nil>} {application/vnd.kubernetes.protobuf application vnd.kubernetes.protobuf false 0xc0002b3000 <nil> 0xc0002b3000 0xc000272570}] 0xc0002aefa0} 0xc0000a0c80 map[]}: error in registering resource: runoncedurationoverrides, resource runoncedurationoverrides must implement SingularNameProvider"
```

I was hoping we might be able to "just" rebase. Though :-)

**Comment by ardaguclu** [comment]
This https://github.com/kubernetes/kubernetes/pull/113542 is the reason of failure. I'll add singularname for our CRD.

**Comment by ardaguclu** [comment]
@ingvagabund could you please tag this bump?. Thanks.

**Pull request merged**
